name: Build and Push Docker Image to ACR

on:
  workflow_dispatch:

env:
  REGISTRY: devnitoracr001.azurecr.io
  ACR_NAME: devnitoracr001
  IMAGE_NAME: starbootgreywithtrivy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            startbootstrap-grayscale-master

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH

      - name: Tag Docker image
        run: |
          docker tag $IMAGE_NAME:latest \
            $REGISTRY/$IMAGE_NAME:Dev

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:Dev
