name: Build and Push Docker Image to ACR

on:
  workflow_dispatch:
   
env:
  REGISTRY: devnitoracr001.azurecr.io
  IMAGE_NAME: starbootgrey

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Login to ACR
      - name: Login to ACR
        run: |
          az acr login --name myacr

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE_NAME:${{ github.sha }} \
            -t $REGISTRY/$IMAGE_NAME:Dev \
            startbootstrap-grayscale-master

      # 5. Push Docker image to ACR
      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker push $REGISTRY/$IMAGE_NAME:Dev
